name: hello wordl!

on: push

jobs: 
  my-job-name: 
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello word FIAP"
      - run: id
      - run: uname -a
      - run: env
      - run: echo ${{ secrets.SEGREDO }} 
