name: hello wordl!

on: workflow_dispatch

jobs: 
  my-job-name: 
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello word FIAP"
      - run: id
      - run: uname -a
      - run: env
      - run: base64 -e ${{ secrets.SEGREDO }} | echo
