name: ZAP by Checkmarx

on: workflow_dispatch 

jobs:
  zap-scan:
    runs-on: ubuntu-latest
    steps:
    - name: ZAP Scan
      uses: zaproxy/action-baseline@v0.13.0
      with:
        target: 'https://juice-shop.herokuapp.com/'
