name: ZAP by Checkmars
on: push
jobs:
  zap-scan:
    runs-on: unbuntu-latest
    steps:
    - name: ZAP Scan
      uses: zaproxy/action-baseline@v0.13.0
      with:
        target: 'https://juice-shop.herokuapp.com/'
